### ISSUE TITLE
Propositions

### ISSUE THREAD

**Issue by Aym3nTN** [Dainerx/InputTounsi#1]
Good Oussama,
I've got some propositions and bugs reports:
1- for the phone number check, it's not working well, i.e.: 72xxxxxx is not accepted, though it's a correct number format (starting by 72)
2- for the Address field (and others), could you add a hint concerning the right format because it's not awkward for everyone.

Keep up the good work 👍

**Comment by Dainerx** [comment]
Hey Aym3nTN, 

I'm really glad you tested InputTounsi, I cannot express how happy I am reading your feedback. 

1. Phone format: not accepting 72xxxxxx was made on purpose. Why? Simply because apps are more likely interested in your mobile number so they can text you back (newsletter...)
2. Hint for address field: Yes this is a very fruitful input of yours, I'll work on it. 

Please always keep in mind that we are still on Alpha version, many features and fixes will be applied once we get to beta version. 

Again, thank you for coming forward. Strongly appreciated.
